name: Build llvm
on:
  push:
    branches:    
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Init repo
      run: |
        cd ~/
        git clone https://github.com/shuxiangfan/tc-build.git tc-build
        
    - name: Grab dependencies
      run: |
        sudo apt update
        sudo apt install bc \
            binutils-dev \
            bison \
            build-essential \
            ca-certificates \
            ccache \
            clang \
            cmake \
            curl \
            file \
            flex \
            git \
            libelf-dev \
            libssl-dev \
            libstdc++-$(apt list libstdc++6 2>/dev/null | grep -Eos '[0-9]+\.[0-9]+\.[0-9]+' | head -1 | cut -d . -f 1)-dev \
            lld \
            make \
            ninja-build \
            python3-dev \
            texinfo \
            u-boot-tools \
            xz-utils \
            zlib1g-dev
    - name: Build cbl
      run: |
        cd ~/tc-build
        chmod a+x build-tc.sh
        bash build-tc.sh
    - name : Upload
      uses: actions/upload-artifact@v4.3.5
      with:
        name: install
        path: /home/runner/tc-build/install
